"""Added a c ompleted column in the courses db

Revision ID: 53eb15c7ea3d
Revises: 
Create Date: 2024-07-22 17:21:47.840075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eb15c7ea3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
