"""Added completed_date to the courses model

Revision ID: 74b4441c1fa2
Revises: 53eb15c7ea3d
Create Date: 2024-07-23 10:15:06.821790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b4441c1fa2'
down_revision = '53eb15c7ea3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
